#!/bin/sh
#
# Spell a file & generate the syntax statements necessary to
# highlight in vim.  Based on a program from Krishna Gadepalli
# <krishna@stdavids.picker.com>.
#
# I use the following mappings (in .vimrc):
#
#   noremap <F8> :so `vimspell.sh %`<CR><CR>
#   noremap <F7> :syntax clear SpellErrors<CR>
#
# Neil Schemenauer <nascheme@ucalgary.ca>
# March 1999
#
# Version not updating original file Petr Kolar <Petr.Kolar@vslib.cz>
# June 2002

OUTFILE=$1

shift
ispell -l $* | sort -u |
awk '
      {
    printf "syntax match SpellErrors \"\\<%s\\>\"\n", $0 ;
      }

END   {
    printf "highlight link SpellErrors ErrorMsg\n\n" ;
      }
' > $OUTFILE
echo "!/bin/rm $OUTFILE" >> $OUTFILE
